[package]
name = "vb_storage"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
arrayvec.workspace = true
blake3.workspace = true
crc32c.workspace = true
fjall.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true
vb_core = { path = "../vb_core" }

[dev-dependencies]
proptest = { workspace = true }
tempfile.workspace = true

[lints]
workspace = true
