//! Tests for the shard module.
#![allow(
    dead_code,
    unused_imports,
    clippy::expect_used,
    clippy::let_underscore_must_use,
    clippy::as_conversions,
    clippy::indexing_slicing
)]

include!("tests/chunk_001.rs");
include!("tests/chunk_002.rs");
include!("tests/chunk_003.rs");
include!("tests/chunk_004.rs");
include!("tests/chunk_005.rs");
include!("tests/chunk_006.rs");
include!("tests/chunk_007.rs");
include!("tests/chunk_008.rs");
include!("tests/chunk_009.rs");
include!("tests/chunk_010.rs");
include!("tests/chunk_011.rs");
include!("tests/chunk_012.rs");
include!("tests/chunk_013.rs");
include!("tests/chunk_014.rs");
include!("tests/chunk_015.rs");
include!("tests/chunk_016.rs");
include!("tests/chunk_017.rs");
include!("tests/chunk_018.rs");
include!("tests/chunk_019.rs");
include!("tests/chunk_020.rs");
include!("tests/chunk_021.rs");
include!("tests/chunk_022.rs");
include!("tests/chunk_023.rs");
include!("tests/chunk_024.rs");
include!("tests/chunk_025.rs");
include!("tests/chunk_026.rs");
include!("tests/chunk_027.rs");
include!("tests/chunk_028.rs");
include!("tests/chunk_029.rs");
include!("tests/chunk_031.rs");
include!("tests/chunk_032.rs");
// vb-8tjk8: snapshot writer tests
include!("tests/chunk_033.rs");
// PO-vb-pymh test coverage
include!("tests/chunk_001_submit_frame_release.rs");
include!("tests/chunk_002_payload_bounds.rs");
include!("tests/chunk_002_cancel_kill_idempotency.rs");
include!("tests/chunk_dispatch_shutdown.rs");
include!("tests/chunk_dispatch_error_semantics.rs");
