// SPDX-License-Identifier: MIT
//
// ============================================================================
// IN-TREE PRODUCTION-SOURCE MIRROR for `checked_step_offset`
// ============================================================================
//
// This file is a VERBATIM mirror of the production arithmetic primitive
// `StepIdx::checked_add` at `crates/vb_core/src/ids/mod.rs:303-308` and the
// production wrapper `checked_step_offset` at
// `crates/vb_compile/src/mod_compile_lowering/part_12.rs:199-212`,
// with minimal substitutions:
//
//   1. The production `StepIdx` newtype is declared locally with a `pub`
//      inner field (production has a private inner field). The
//      constructor / accessor surface (`new`, `get`, `from_int`) is
//      preserved verbatim.
//
//   2. The production error variant `CompileError::PrimitiveLoweringLimitExceeded`
//      at `crates/vb_compile/src/mod_compile_errors/kind.rs:124` is
//      mirrored as `SpecCompileError::PrimitiveLoweringLimitExceeded`.
//      Field shape (4 payload fields: primitive, field, value, limit)
//      is preserved; field types are abstracted from `usize` to `u64`
//      to match the spec arithmetic model.
//
//   3. The production exec fn `checked_step_offset` is reproduced
//      verbatim from part_12.rs:199-212 and wrapped in
//      `#[verifier::external]` so Verus skips body verification. The
//      spec contract is attached via `assume_specification` in the
//      companion spec file `verification/verus/step_offset.rs`.
//
// ============================================================================
// WHY NOT DIRECT `#[path]` INCLUSION OF part_12.rs
// ============================================================================
//
// Direct inclusion of `crates/vb_compile/src/mod_compile_lowering/part_12.rs`
// is blocked by:
//   - `use super::*;` resolves to `vb_compile::mod_compile_lowering::*`
//     which fails when the file is included from `verification/verus/`
//     (no such parent module exists in this single-file Verus unit).
//   - The production file imports `vb_core::ids::StepIdx` which is
//     generated by a `macro_rules!` newtype.
//   - The production file uses `CompileError` from `vb_compile::mod_compile_errors`
//     whose `#[derive(thiserror::Error, ...)]` is not proc-macro-safe in
//     this single-file Verus unit.
//
// The verbatim production-mirror pattern sidesteps every blocker. Drift
// between this mirror and the production source (renamed field, type
// change, arity change, body change) breaks the `extern_step_offset`
// Verus build at compile time.
//
// ============================================================================
// DRIFT POLICY
// ============================================================================
//
// Any drift between this file and the production source MUST be mirrored
// here. Drift in `StepIdx` field name, `checked_add` body, or
// `checked_step_offset` body breaks the mirror at compile time.
//
// ============================================================================
// TRUST BOUNDARY (GOD RULE 2 transparency)
// ============================================================================
//
// The production bodies of `StepIdx::checked_add` and `checked_step_offset`
// are NOT verified by Verus. Each exec fn is marked `#[verifier::external]`
// so Verus skips body verification. The companion spec file
// `verification/verus/step_offset.rs` attaches `assume_specification`
// contracts that the spec proofs discharge. Drift between this mirror
// and the production source is reported as binding-debt tracked
// outside Verus.
// ============================================================================

#![forbid(unsafe_code)]
#![allow(dead_code)]
#![allow(non_snake_case)]

use vstd::prelude::*;

verus! {

// ---------------------------------------------------------------------------
// VERBATIM PRODUCTION: StepIdx newtype
// ---------------------------------------------------------------------------
//
// Source: crates/vb_core/src/ids/mod.rs:55 (u16 newtype).
// The production struct is `pub struct StepIdx(u16)` (private field).
// The mirror exposes the inner field as `pub` so the spec proofs can
// name `id.0` for arithmetic reasoning.

#[derive(Clone, Copy, PartialEq, Eq)]
pub struct StepIdx(pub u16);

impl StepIdx {
    /// Mirror of `StepIdx::new(value: u16) -> Self` at
    /// `crates/vb_core/src/ids/mod.rs:21` (generated by
    /// `numeric_id!` macro).
    pub const fn new(value: u16) -> Self {
        Self(value)
    }

    /// Spec constructor for `StepIdx` from a non-negative `int`.
    /// Mirrors `StepIdx::new(value: u16) -> Self` for values that
    /// fit in u16 (so the spec proof can construct boundary values
    /// without going through the exec `new` constructor).
    /// NOTE: spec-mode helper; defined here in `impl` so it
    /// inherits the `StepIdx` self-type. Requires `verus!` context.
    pub open spec fn from_int(value: int) -> Self {
        Self(value as u16)
    }

    /// Mirror of `StepIdx::get(self) -> u16` at
    /// `crates/vb_core/src/ids/mod.rs:27` (generated by
    /// `numeric_id!` macro accessor named `get`).
    pub const fn get(self) -> u16 {
        self.0
    }

    /// Mirror of `StepIdx::checked_add(self, rhs: u16) -> Option<Self>`
    /// at `crates/vb_core/src/ids/mod.rs:303-308`:
    ///
    /// ```ignore
    /// pub const fn checked_add(self, rhs: u16) -> Option<Self> {
    ///     match self.0.checked_add(rhs) {
    ///         Some(value) => Some(Self(value)),
    ///         None => None,
    ///     }
    /// }
    /// ```
    ///
    /// `#[verifier::external]` so Verus does not attempt to verify the
    /// body. The spec contract is attached via `assume_specification`
    /// in `step_offset.rs`.
    #[verifier::external]
    pub fn checked_add(self, rhs: u16) -> Option<Self> {
        match self.0.checked_add(rhs) {
            Some(value) => Some(Self(value)),
            None => None,
        }
    }
}

// ---------------------------------------------------------------------------
// VERBATIM PRODUCTION: PrimitiveLoweringLimitExceeded variant
// ---------------------------------------------------------------------------
//
// Source: crates/vb_compile/src/mod_compile_errors/kind.rs:124.
//
// Mirror of `CompileError::PrimitiveLoweringLimitExceeded` at
// `crates/vb_compile/src/mod_compile_errors/kind.rs:124`. This is the
// exact variant constructed by the production `checked_step_offset`
// wrapper at part_12.rs:206-211 when `StepIdx::checked_add` returns
// `None`.
//
// The production variant carries four payload fields
// (`primitive: &'static str, field: &'static str, value: usize,
// limit: usize`). For the purpose of this binding we mirror only the
// discriminant — the spec proofs reason about whether the function
// returned Ok or Err, not about the error payload contents. Field
// types are still mirrored structurally to surface drift (renamed
// field, type change, or arity change breaks the mirror).

#[derive(Clone, Copy)]
pub enum SpecCompileError {
    /// Production: `CompileError::PrimitiveLoweringLimitExceeded`
    /// at `crates/vb_compile/src/mod_compile_errors/kind.rs:124`.
    /// The four payload fields are present structurally but the
    /// spec proofs do not inspect them.
    PrimitiveLoweringLimitExceeded {
        primitive: &'static str,
        field: &'static str,
        value: u64,
        limit: u64,
    },
}

// ---------------------------------------------------------------------------
// VERBATIM PRODUCTION: checked_step_offset wrapper
// ---------------------------------------------------------------------------
//
// Source: crates/vb_compile/src/mod_compile_lowering/part_12.rs:199-212.
//
// ```ignore
// pub(super) fn checked_step_offset(
//     id: StepIdx,
//     offset: u16,
//     primitive: &'static str,
//     field: &'static str,
// ) -> Result<StepIdx, CompileError> {
//     id.checked_add(offset)
//         .ok_or(CompileError::PrimitiveLoweringLimitExceeded {
//             primitive,
//             field,
//             value: id.as_usize(),
//             limit: usize::from(u16::MAX),
//         })
// }
// ```
//
// The four production arguments are preserved exactly. The body is
// opaque to Verus; the spec file attaches an `assume_specification`
// contract that the spec proofs discharge.

/// Mirror of `checked_step_offset(id: StepIdx, offset: u16, primitive:
/// &'static str, field: &'static str) -> Result<StepIdx, CompileError>`
/// at `crates/vb_compile/src/mod_compile_lowering/part_12.rs:199-212`.
#[verifier::external]
pub fn checked_step_offset(
    id: StepIdx,
    offset: u16,
    primitive: &'static str,
    field: &'static str,
) -> Result<StepIdx, SpecCompileError> {
    id.checked_add(offset).ok_or(SpecCompileError::PrimitiveLoweringLimitExceeded {
        primitive,
        field,
        value: id.get() as u64,
        limit: u16::MAX as u64,
    })
}

} // verus!