[package]
name = "vb_core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bytes.workspace = true
chrono.workspace = true
indexmap.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
postcard.workspace = true
proptest = { workspace = true }

[[bench]]
name = "aggregate_resource_budget"
harness = false

[features]
default = []
bench = []
volatile = []
test-util = []

[lints]
workspace = true
