[package]
name = "vb_core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bytes.workspace = true
chrono.workspace = true
indexmap.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
blake3.workspace = true
criterion.workspace = true
postcard.workspace = true
proptest = { workspace = true }
serde_json.workspace = true

[[bench]]
name = "aggregate_resource_budget"
harness = false

[features]
bench = []
default = []
kani-diagnostic-codes = []
kani-vb-ajc40 = []
test-util = []
volatile = []

[lints]
workspace = true
