[package]
name = "vb_yaml"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
saphyr.workspace = true
saphyr-parser.workspace = true
thiserror.workspace = true
vb_core = { path = "../vb_core" }

[dev-dependencies]
indoc.workspace = true
proptest = { workspace = true }

[features]
test-util = []

[lints]
workspace = true
