// Code entries for the [`CodeCategory::Accessor`] category (E13xx, 0x1301–0x1315).
// // This file is a data file intended for inclusion via the `include!` macro.

CodeEntry {
    symbolic: "ACCESSOR_CONST_OUT_OF_BOUNDS",
    numeric: 0x1315,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "CORE_QUEUE_FULL",
    numeric: 0x1301,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "RESOURCE_LIMIT_EXCEEDED",
    numeric: 0x1302,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "ALLOCATION_FAILED",
    numeric: 0x1303,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "EXPRESSION_STACK_OVERFLOW",
    numeric: 0x1304,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "MISSING_OUTPUT_SLOT",
    numeric: 0x1305,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "STEP_STATE_OUT_OF_BOUNDS",
    numeric: 0x1306,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "INVALID_COMPILED_WORKFLOW_CORE",
    numeric: 0x1307,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "UNSUPPORTED_PRIMITIVE",
    numeric: 0x1308,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "UNSUPPORTED_ACCESSOR_TRAVERSAL",
    numeric: 0x130A,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "EXPRESSION_STACK_UNDERFLOW",
    numeric: 0x130B,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "OBJECT_FIELD_NOT_FOUND",
    numeric: 0x130C,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "LIST_INDEX_OUT_OF_BOUNDS",
    numeric: 0x130D,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "SYMBOL_OUT_OF_BOUNDS",
    numeric: 0x1311,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "LIST_OUT_OF_BOUNDS",
    numeric: 0x1312,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "OBJECT_OUT_OF_BOUNDS",
    numeric: 0x1313,
    category: CodeCategory::Accessor,
    deprecated: false,
},
CodeEntry {
    symbolic: "BLOB_OUT_OF_BOUNDS",
    numeric: 0x1314,
    category: CodeCategory::Accessor,
    deprecated: false,
},
