//! Code entries for the [`CodeCategory::RuntimeBoundary`] category —
//! storage and journal boundary codes (E40xx, 0x4001–0x4020).

/// Per-category `CodeEntry` slice for the RuntimeBoundary storage/journal codes.
pub(super) const ENTRIES: &[super::CodeEntry] = &[
    super::CodeEntry {
        symbolic: "JOURNAL_FJALL",
        numeric: 0x4001,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_ENCODE",
        numeric: 0x4002,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_KEY_CAPACITY",
        numeric: 0x4003,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_DUPLICATE_EVENT",
        numeric: 0x4004,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_WRITE_LOCK_POISONED",
        numeric: 0x4005,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_QUEUE_CAPACITY",
        numeric: 0x4006,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_QUEUE_FULL",
        numeric: 0x4007,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_BATCH_BYTES_EXCEEDED",
        numeric: 0x402F,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_UNEXPECTED_TRAILING_BYTES",
        numeric: 0x4030,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_WRONG_RUN",
        numeric: 0x4008,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_SEQUENCE_GAP",
        numeric: 0x4009,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_SEQUENCE_OVERFLOW",
        numeric: 0x400A,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_BAD_MAGIC",
        numeric: 0x400B,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_UNSUPPORTED_SCHEMA",
        numeric: 0x400C,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_MIGRATION_REQUIRED",
        numeric: 0x400D,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_UNKNOWN_RECORD_KIND",
        numeric: 0x400E,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_FAMILY_MISMATCH",
        numeric: 0x400F,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_HEADER_LENGTH_MISMATCH",
        numeric: 0x4010,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_PAYLOAD_TOO_LARGE",
        numeric: 0x4011,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_HEADER_CHECKSUM",
        numeric: 0x4012,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_PAYLOAD_DIGEST_MISMATCH",
        numeric: 0x4013,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_UNEXPECTED_EOF",
        numeric: 0x4014,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_POSTCARD_DECODE",
        numeric: 0x4015,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_QUEUE_SHUTDOWN",
        numeric: 0x4016,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_ARTIFACT_MALFORMED",
        numeric: 0x4017,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_ARTIFACT_CHECKSUM",
        numeric: 0x4018,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_INVALID_GATE_COUNT",
        numeric: 0x401C,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_MISSING_PROOF_FLAG",
        numeric: 0x401D,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_ARTIFACT_NOT_FOUND",
        numeric: 0x4019,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_PROCESS_LOCK_HELD",
        numeric: 0x401A,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_PROCESS_LOCK_IO",
        numeric: 0x401B,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_TOO_MANY_EVENTS",
        numeric: 0x401E,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_REPLAY_ALLOC_FAIL",
        numeric: 0x401F,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_INVALID_EVENT",
        numeric: 0x4020,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_PAYLOAD_LEN_OVERFLOW",
        numeric: 0x4037,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_INDEX_STATUS_STATE_COLLISION",
        numeric: 0x4038,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_RESERVED_SEQ_SENTINEL",
        numeric: 0x4039,
        category: super::CodeCategory::RuntimeBoundary,
        deprecated: false,
    },
];
