//! Code entries for the [`CodeCategory::Storage`] category — runtime
//! storage and journal codes (E20xx, 0x2001–0x201F).

/// Per-category `CodeEntry` slice for the runtime storage codes.
pub(super) const ENTRIES: &[super::CodeEntry] = &[
    super::CodeEntry {
        symbolic: "QUEUE_FULL",
        numeric: 0x2001,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "RUN_NOT_FOUND",
        numeric: 0x2002,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ACTIVE_RUN_CAPACITY_EXCEEDED",
        numeric: 0x2003,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "RUN_ALREADY_EXISTS",
        numeric: 0x2004,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "UNSUPPORTED_OPERATION",
        numeric: 0x2005,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "SHUTDOWN_IN_PROGRESS",
        numeric: 0x2006,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_POISONED",
        numeric: 0x2007,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "STORAGE_JOURNAL_APPEND_FAILED",
        numeric: 0x2008,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "UNSUPPORTED_ASYNC_STRICT_ACK",
        numeric: 0x2009,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "FRAME_POOL_UNAVAILABLE",
        numeric: 0x200A,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "INVALID_ACTION_COMPLETION",
        numeric: 0x200B,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "INVALID_TIMER_FIRE",
        numeric: 0x200C,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "UNSUPPORTED_FULL_RECOVERY_HYDRATION",
        numeric: 0x200D,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "INVALID_RECOVERY_HYDRATION",
        numeric: 0x200E,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "COMMAND_QUEUE_CAPACITY_EXCEEDED",
        numeric: 0x200F,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ACTIVE_RUN_CAPACITY_ZERO",
        numeric: 0x2010,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ADMISSION_ARTIFACT_NOT_FOUND",
        numeric: 0x2011,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ADMISSION_CAPABILITY_DENIED",
        numeric: 0x2012,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ENCODE_FAILED",
        numeric: 0x2013,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ADMISSION_ARTIFACT_INVALID",
        numeric: 0x2014,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ADMISSION_HEADER_PERSISTENCE_FAILED",
        numeric: 0x2015,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "SECRET_RESULT_NOT_ALLOWED",
        numeric: 0x2016,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "IPC_PAYLOAD_SIZE_EXCEEDED",
        numeric: 0x2017,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ADMISSION_ARTIFACT_DIGEST_MISMATCH",
        numeric: 0x2018,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ADMISSION_ARTIFACT_STALE",
        numeric: 0x2019,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ADMISSION_DIGEST_MISMATCH",
        numeric: 0x201A,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "ENGINE_DRIVE_FAILED",
        numeric: 0x201B,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "SHARD_NOT_FOUND",
        numeric: 0x201C,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "MIGRATE_SELF",
        numeric: 0x201D,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "JOURNAL_FULL",
        numeric: 0x201E,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
    super::CodeEntry {
        symbolic: "INPUT_MAPPING_FAILED",
        numeric: 0x201F,
        category: super::CodeCategory::Storage,
        deprecated: false,
    },
];
