// Code entries for the [`CodeCategory::Storage`] category — runtime
// storage and journal codes (E20xx, 0x2001–0x201F).
// // This file is a data file intended for inclusion via the `include!` macro.

CodeEntry {
    symbolic: "QUEUE_FULL",
    numeric: 0x2001,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "RUN_NOT_FOUND",
    numeric: 0x2002,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ACTIVE_RUN_CAPACITY_EXCEEDED",
    numeric: 0x2003,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "RUN_ALREADY_EXISTS",
    numeric: 0x2004,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "UNSUPPORTED_OPERATION",
    numeric: 0x2005,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "SHUTDOWN_IN_PROGRESS",
    numeric: 0x2006,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "JOURNAL_POISONED",
    numeric: 0x2007,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "STORAGE_JOURNAL_APPEND_FAILED",
    numeric: 0x2008,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "UNSUPPORTED_ASYNC_STRICT_ACK",
    numeric: 0x2009,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "FRAME_POOL_UNAVAILABLE",
    numeric: 0x200A,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "INVALID_ACTION_COMPLETION",
    numeric: 0x200B,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "INVALID_TIMER_FIRE",
    numeric: 0x200C,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "UNSUPPORTED_FULL_RECOVERY_HYDRATION",
    numeric: 0x200D,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "INVALID_RECOVERY_HYDRATION",
    numeric: 0x200E,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "COMMAND_QUEUE_CAPACITY_EXCEEDED",
    numeric: 0x200F,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ACTIVE_RUN_CAPACITY_ZERO",
    numeric: 0x2010,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ADMISSION_ARTIFACT_NOT_FOUND",
    numeric: 0x2011,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ADMISSION_CAPABILITY_DENIED",
    numeric: 0x2012,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ENCODE_FAILED",
    numeric: 0x2013,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ADMISSION_ARTIFACT_INVALID",
    numeric: 0x2014,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ADMISSION_HEADER_PERSISTENCE_FAILED",
    numeric: 0x2015,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "SECRET_RESULT_NOT_ALLOWED",
    numeric: 0x2016,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "IPC_PAYLOAD_SIZE_EXCEEDED",
    numeric: 0x2017,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ADMISSION_ARTIFACT_DIGEST_MISMATCH",
    numeric: 0x2018,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ADMISSION_ARTIFACT_STALE",
    numeric: 0x2019,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ADMISSION_DIGEST_MISMATCH",
    numeric: 0x201A,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "ENGINE_DRIVE_FAILED",
    numeric: 0x201B,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "SHARD_NOT_FOUND",
    numeric: 0x201C,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "MIGRATE_SELF",
    numeric: 0x201D,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "JOURNAL_FULL",
    numeric: 0x201E,
    category: CodeCategory::Storage,
    deprecated: false,
},
CodeEntry {
    symbolic: "INPUT_MAPPING_FAILED",
    numeric: 0x201F,
    category: CodeCategory::Storage,
    deprecated: false,
},
