#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ParseError {
    MissingArgument(&'static str),
    UnknownEmitTarget(String),
    UnknownDurability(String),
    UnknownProfile(String),
    UnknownCommand(String),
    UnknownServerMode(String),
    UnknownEventStatus(String),
    InvalidAgentContextArgument(String),
    InvalidTraceArgument(String),
    InvalidStatusArgument(String),
    InvalidSystemStatusArgument(String),
    UnknownActionCommand(String),
    UnknownActionRegistry(String),
    MissingActionRegistryValue,
    UnknownActionListFlag(String),
    UnexpectedActionListArgument(String),
    InvalidActionListArgument(String),
    UnknownActionInspectFlag(String),
    UnexpectedActionInspectArgument(String),
    InvalidActionInspectArgument(String),
    InvalidActionId(String),
    InvalidActionName(String),
    UnknownFlag { command: &'static str, flag: String },
    InvalidArgument(String),
    NoCommand,
    InvalidStep(String),
    ReasonTooLong,
}
