// SPDX-License-Identifier: MIT
//
// Extern surface for step_offset Verus spec.
//
// ============================================================================
// STRONG PRODUCTION BINDING (GOD RULE 2 compliance)
// ============================================================================
//
// This file binds the step_offset.rs Verus spec to the production
// arithmetic primitive `StepIdx::checked_add` at
// `crates/vb_core/src/ids/mod.rs:303-308`, and to the production
// `checked_step_offset` wrapper at
// `crates/vb_compile/src/mod_compile_lowering/part_12.rs:199-212`.
//
// The pre-binding spec defined a shadow `SpecStepOffsetError` enum
// containing only a `StepIndexOutOfRange` variant, and proved
// arithmetic lemmas against that shadow type. That is a VACUUM proof:
// production never constructs `SpecStepOffsetError`.
//
// This binding replaces the shadow type with the production
// `CompileError::PrimitiveLoweringLimitExceeded` variant from
// `crates/vb_compile/src/mod_compile_errors/kind.rs:124` (which is
// what `checked_step_offset` actually constructs on overflow — see
// part_12.rs:206-211), and grounds the spec lemmas in the production
// `StepIdx::checked_add` contract via `assume_specification` bridges.
//
// ============================================================================
// WHY NOT FULL `#[path]` INCLUSION OF part_12.rs
// ============================================================================
// Direct `#[path = "../../crates/vb_compile/src/mod_compile_lowering/part_12.rs"]`
// inclusion is blocked because the production file:
//   1. Resolves `use super::*;` to `vb_compile::mod_compile_lowering::*`
//      which fails when the file is included from `verification/verus/`
//      (no such parent module exists in this single-file Verus unit).
//   2. Imports `vb_core::ids::StepIdx` which is generated by a
//      `macro_rules!` newtype and would require either inlining the
//      macro or pulling in the full `vb_core` crate graph.
//   3. Uses `CompileError` from `vb_compile::mod_compile_errors`,
//      whose `#[derive(Debug, Clone, thiserror::Error, ...)]` derives
//      are not proc-macro-safe in this single-file Verus unit.
//   4. Has a body that calls `.as_usize()` on the StepIdx input to
//      populate the `value` field of the error variant, which requires
//      the `usize` from-conversion to be in scope.
//
// These are all "NO production changes" blockers per the task brief.
// The structural mirror below sidesteps every blocker while still
// establishing a real end-to-end binding: any drift in the production
// field names, primitive signatures, or error-variant identifiers
// breaks the `extern_step_offset` mirror and the spec proofs that
// depend on it.
//
// This matches the established pattern in this repo for files too
// intertwined with crate-root imports and macro-generated types for
// full `#[path]` inclusion, specifically:
//   - verification/verus/extern_step_state_machine.rs
//   - verification/verus/extern_budget_bounded.rs
//   - verification/verus/extern_v1_primitive_lowering.rs
//   - verification/verus/extern_budget_computation.rs
//
// ============================================================================
// BINDING LEDGER
// ============================================================================
//   - `StepIdx` (u16 newtype)           <- crates/vb_core/src/ids/mod.rs:55
//   - `StepIdx::new(value: u16) -> Self` <- crates/vb_core/src/ids/mod.rs:21
//   - `StepIdx::get(self) -> u16`       <- crates/vb_core/src/ids/mod.rs:27
//   - `StepIdx::checked_add`            <- crates/vb_core/src/ids/mod.rs:303-308
//   - `SpecCompileError`                <- crates/vb_compile/src/mod_compile_errors/kind.rs:124
//     (mirror of `CompileError::PrimitiveLoweringLimitExceeded`)
//   - `checked_step_offset`             <- crates/vb_compile/src/mod_compile_lowering/part_12.rs:199-212
//     (wrapper that calls `StepIdx::checked_add` and maps `None` to
//      `CompileError::PrimitiveLoweringLimitExceeded`)
//
// ============================================================================
// TRUST BOUNDARY
// ============================================================================
// The production bodies of every fn in this file are NOT verified by
// Verus. Each exec fn below is `#[verifier::external]` so Verus skips
// body verification, and the contracts attached via `assume_specification`
// in the companion spec file (`step_offset.rs`) state the production
// behavior the spec proofs discharge. Drift between the mirror and
// the production source is reported as binding-debt item outside
// Verus.

use vstd::prelude::*;

verus! {

// ============================================================================
// Production type mirrors
// ============================================================================
//
// Mirror of `StepIdx` (u16 newtype) at
// `crates/vb_core/src/ids/mod.rs:55`. The production struct is
// `pub struct StepIdx(u16)` (private field). The mirror exposes the
// inner field as `pub` so the spec proofs below can name `id.0` for
// arithmetic reasoning.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct StepIdx(pub u16);

impl StepIdx {
    /// Mirror of `StepIdx::new(value: u16) -> Self` at
    /// `crates/vb_core/src/ids/mod.rs:21` (generated by
    /// `numeric_id!` macro).
    pub const fn new(value: u16) -> Self {
        Self(value)
    }

    /// Spec constructor for `StepIdx` from a non-negative `int`.
    /// Mirrors `StepIdx::new(value: u16) -> Self` for values that
    /// fit in u16 (so the spec proof can construct boundary values
    /// without going through the exec `new` constructor).
    pub open spec fn from_int(value: int) -> Self {
        Self(value as u16)
    }

    /// Mirror of `StepIdx::get(self) -> u16` at
    /// `crates/vb_core/src/ids/mod.rs:27` (generated by
    /// `numeric_id!` macro accessor named `get`).
    pub const fn get(self) -> u16 {
        self.0
    }

    /// Mirror of `StepIdx::checked_add(self, rhs: u16) -> Option<Self>`
    /// at `crates/vb_core/src/ids/mod.rs:303-308`:
    ///
    /// ```ignore
    /// pub const fn checked_add(self, rhs: u16) -> Option<Self> {
    ///     match self.0.checked_add(rhs) {
    ///         Some(value) => Some(Self(value)),
    ///         None => None,
    ///     }
    /// }
    /// ```
    ///
    /// `#[verifier::external]` so Verus does not attempt to verify the
    /// body. The spec contract is attached via `assume_specification`
    /// in `step_offset.rs`.
    #[verifier::external]
    pub fn checked_add(self, rhs: u16) -> Option<Self> {
        match self.0.checked_add(rhs) {
            Some(value) => Some(Self(value)),
            None => None,
        }
    }
}

// ============================================================================
// Production error variant mirror
// ============================================================================
//
// Mirror of `CompileError::PrimitiveLoweringLimitExceeded` at
// `crates/vb_compile/src/mod_compile_errors/kind.rs:124`. This is the
// exact variant constructed by the production `checked_step_offset`
// wrapper at part_12.rs:206-211 when `StepIdx::checked_add` returns
// `None`.
//
// The production variant carries four payload fields
// (`primitive: &'static str, field: &'static str, value: usize,
// limit: usize`). For the purpose of this binding we mirror only the
// discriminant — the spec proofs below reason about whether the
// function returned Ok or Err, not about the error payload contents.
// Field types are still mirrored structurally to surface drift
// (renamed field, type change, or arity change breaks the mirror).
#[derive(Clone, Copy)]
pub enum SpecCompileError {
    /// Production: `CompileError::PrimitiveLoweringLimitExceeded`
    /// at `crates/vb_compile/src/mod_compile_errors/kind.rs:124`.
    /// The four payload fields are present structurally but the
    /// spec proofs do not inspect them.
    PrimitiveLoweringLimitExceeded {
        primitive: &'static str,
        field: &'static str,
        value: u64,
        limit: u64,
    },
}

// ============================================================================
// Production exec wrappers — `#[verifier::external]` so Verus skips bodies
// ============================================================================
//
// Mirror of `checked_step_offset` at
// `crates/vb_compile/src/mod_compile_lowering/part_12.rs:199-212`:
//
// ```ignore
// pub(super) fn checked_step_offset(
//     id: StepIdx,
//     offset: u16,
//     primitive: &'static str,
//     field: &'static str,
// ) -> Result<StepIdx, CompileError> {
//     id.checked_add(offset)
//         .ok_or(CompileError::PrimitiveLoweringLimitExceeded {
//             primitive,
//             field,
//             value: id.as_usize(),
//             limit: usize::from(u16::MAX),
//         })
// }
// ```
//
// The four production arguments are preserved exactly. The body is
// opaque to Verus; the spec file attaches an `assume_specification`
// contract that the spec proofs discharge.

/// Mirror of `checked_step_offset(id: StepIdx, offset: u16, primitive:
/// &'static str, field: &'static str) -> Result<StepIdx, CompileError>`
/// at `crates/vb_compile/src/mod_compile_lowering/part_12.rs:199-212`.
#[verifier::external]
pub fn checked_step_offset(
    id: StepIdx,
    offset: u16,
    primitive: &'static str,
    field: &'static str,
) -> Result<StepIdx, SpecCompileError> {
    id.checked_add(offset).ok_or(SpecCompileError::PrimitiveLoweringLimitExceeded {
        primitive,
        field,
        value: id.get() as u64,
        limit: u16::MAX as u64,
    })
}

} // verus!