#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import hashlib


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "verification/verus/vb_ajc40_admission_kernel.source"
PRODUCTION = ROOT / "crates/vb_core/src/workflow/admission_kernel.rs"
VERUS = ROOT / "verification/verus/vb_ajc40_admission_kernel_scalar.rs"


def source_hash() -> str:
    return hashlib.sha256(SOURCE.read_bytes()).hexdigest()


def production_text(digest: str) -> str:
    return f'''#![forbid(unsafe_code)]
//! Scalar post-decode admission kernel shared by compiled slug/query validation.
//!
//! GENERATED by `verification/verus/generate_vb_ajc40_admission_kernel.py`.
//! Source: `verification/verus/vb_ajc40_admission_kernel.source`.
//! Source sha256: {digest}.
//! Verus output: `verification/verus/vb_ajc40_admission_kernel_scalar.rs`.

/// Scalar admission decision for decoded bounded-accessor collections.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AdmissionKernelError {{
    /// Decoded collection has more entries than the production hard limit.
    TooManyItems,
    /// At least one decoded path exceeds the production path-depth limit.
    PathTooDeep,
    /// Recomputed per-item yield total does not match serialized metadata.
    TotalYieldCostMismatch,
    /// Recomputed yield total exceeds caller admission budget.
    YieldBudgetExceeded,
}}

/// Validates count/path/total/budget admission facts and returns remaining budget.
///
/// This function is deliberately scalar and side-effect free so production slug
/// and query validators can share one deterministic seam after postcard decode
/// and checked per-item total recomputation.
pub const fn validate_admission_summary(
    count: usize,
    max_count: usize,
    max_path_depth: usize,
    max_path_segments: usize,
    recomputed_total: u64,
    declared_total_yield_cost: u64,
    max_yield_budget: u64,
) -> Result<u64, AdmissionKernelError> {{
    if count > max_count {{
        return Err(AdmissionKernelError::TooManyItems);
    }}
    validate_admission_depth_total_budget(
        max_path_depth,
        max_path_segments,
        recomputed_total,
        declared_total_yield_cost,
        max_yield_budget,
    )
}}

const fn validate_admission_depth_total_budget(
    max_path_depth: usize,
    max_path_segments: usize,
    recomputed_total: u64,
    declared_total_yield_cost: u64,
    max_yield_budget: u64,
) -> Result<u64, AdmissionKernelError> {{
    if max_path_depth > max_path_segments {{
        return Err(AdmissionKernelError::PathTooDeep);
    }}
    if declared_total_yield_cost != recomputed_total {{
        return Err(AdmissionKernelError::TotalYieldCostMismatch);
    }}
    remaining_yield_budget(recomputed_total, max_yield_budget)
}}

const fn remaining_yield_budget(
    recomputed_total: u64,
    max_yield_budget: u64,
) -> Result<u64, AdmissionKernelError> {{
    match max_yield_budget.checked_sub(recomputed_total) {{
        Some(remaining) => Ok(remaining),
        None => Err(AdmissionKernelError::YieldBudgetExceeded),
    }}
}}

/// Adds one per-item yield cost to an accumulated total with overflow rejection.
pub const fn accumulate_yield_cost(
    total: u64,
    item_cost: u64,
) -> Result<u64, AdmissionKernelError> {{
    match total.checked_add(item_cost) {{
        Some(next) => Ok(next),
        None => Err(AdmissionKernelError::YieldBudgetExceeded),
    }}
}}
'''


def verus_text(digest: str) -> str:
    return f'''//! GENERATED by `verification/verus/generate_vb_ajc40_admission_kernel.py`.
//! Source: `verification/verus/vb_ajc40_admission_kernel.source`.
//! Source sha256: {digest}.
//! Production output: `crates/vb_core/src/workflow/admission_kernel.rs`.
//! Verus output: `verification/verus/vb_ajc40_admission_kernel_scalar.rs`.
use vstd::prelude::*;

verus! {{

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AdmissionKernelError {{
    TooManyItems,
    PathTooDeep,
    TotalYieldCostMismatch,
    YieldBudgetExceeded,
}}

pub open spec fn result_is_ok_u64(result: Result<u64, AdmissionKernelError>) -> bool {{
    matches!(result, Ok(_))
}}

pub open spec fn result_value_u64(result: Result<u64, AdmissionKernelError>) -> int
    recommends
        result_is_ok_u64(result),
{{
    match result {{
        Ok(value) => value as int,
        Err(_) => 0,
    }}
}}

pub open spec fn result_error_u64(result: Result<u64, AdmissionKernelError>) -> AdmissionKernelError
    recommends
        !result_is_ok_u64(result),
{{
    match result {{
        Ok(_) => AdmissionKernelError::YieldBudgetExceeded,
        Err(error) => error,
    }}
}}

pub fn validate_admission_summary(
    count: usize,
    max_count: usize,
    max_path_depth: usize,
    max_path_segments: usize,
    recomputed_total: u64,
    declared_total_yield_cost: u64,
    max_yield_budget: u64,
) -> (result: Result<u64, AdmissionKernelError>)
    ensures
        count > max_count ==> !result_is_ok_u64(result) && result_error_u64(result)
            == AdmissionKernelError::TooManyItems,
        count <= max_count && max_path_depth > max_path_segments ==> !result_is_ok_u64(result)
            && result_error_u64(result) == AdmissionKernelError::PathTooDeep,
        count <= max_count && max_path_depth <= max_path_segments && declared_total_yield_cost
            != recomputed_total ==> !result_is_ok_u64(result) && result_error_u64(result)
            == AdmissionKernelError::TotalYieldCostMismatch,
        count <= max_count && max_path_depth <= max_path_segments && declared_total_yield_cost
            == recomputed_total && recomputed_total > max_yield_budget ==> !result_is_ok_u64(result)
            && result_error_u64(result) == AdmissionKernelError::YieldBudgetExceeded,
        count <= max_count && max_path_depth <= max_path_segments && declared_total_yield_cost
            == recomputed_total && recomputed_total <= max_yield_budget ==> result_is_ok_u64(result)
            && result_value_u64(result) == max_yield_budget as int - recomputed_total as int,
{{
    if count > max_count {{
        return Err(AdmissionKernelError::TooManyItems);
    }}
    if max_path_depth > max_path_segments {{
        return Err(AdmissionKernelError::PathTooDeep);
    }}
    if declared_total_yield_cost != recomputed_total {{
        return Err(AdmissionKernelError::TotalYieldCostMismatch);
    }}
    if recomputed_total > max_yield_budget {{
        return Err(AdmissionKernelError::YieldBudgetExceeded);
    }}
    match max_yield_budget.checked_sub(recomputed_total) {{
        Some(remaining) => Ok(remaining),
        None => Err(AdmissionKernelError::YieldBudgetExceeded),
    }}
}}

pub fn accumulate_yield_cost(total: u64, item_cost: u64) -> (result: Result<
    u64,
    AdmissionKernelError,
>)
    ensures
        total as int + item_cost as int <= u64::MAX as int ==> result_is_ok_u64(result)
            && result_value_u64(result) == total as int + item_cost as int,
        total as int + item_cost as int > u64::MAX as int ==> !result_is_ok_u64(result)
            && result_error_u64(result) == AdmissionKernelError::YieldBudgetExceeded,
{{
    match total.checked_add(item_cost) {{
        Some(next) => Ok(next),
        None => Err(AdmissionKernelError::YieldBudgetExceeded),
    }}
}}

/// Every usize value is non-negative. This property is needed for the
/// empty-path admission case where path depth is 0, which is always <=
/// any valid max_path_segments (a usize >= 0).
pub proof fn proof_empty_root_path_not_too_deep(max_path_segments: usize)
    ensures
        0usize <= max_path_segments,
{{
    assert(0usize <= max_path_segments);
}}

}} // verus!
'''


def write_if_changed(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def main() -> None:
    digest = source_hash()
    write_if_changed(PRODUCTION, production_text(digest))
    write_if_changed(VERUS, verus_text(digest))


if __name__ == "__main__":
    main()
