vcs:
  client: git
  provider: github
  defaultBranch: main

projects:
  velvet-ballistics: '.'

defaultProject: velvet-ballistics

versionConstraint: '>=1.0.0'

pipeline:
  installDependencies: false
  syncWorkspace: true

telemetry: false
