[package]
name = "vb_benchmark"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true
serde_json.workspace = true
kani = { version = "0.0.1", optional = true }

[[bench]]
name = "aggregate_resource_budget"
harness = false

[features]
kani-harnesses = ["kani"]

[lints]
workspace = true
