[package]
name = "vb-compiler"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
blake3.workspace = true
saphyr.workspace = true
saphyr-parser.workspace = true
serde-saphyr.workspace = true
thiserror.workspace = true
vb-core = { path = "../vb-core" }

[lints]
workspace = true
