[package]
name = "vb-storage"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrayvec.workspace = true
fjall.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true
vb-core = { path = "../vb-core" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
