#![allow(dead_code)]
include!("evidence/release_contract.rs");
include!("evidence/release_validation.rs");
include!("evidence/tooling_and_gate_types.rs");
include!("evidence/bundle.rs");
include!("evidence/error_profile_domain.rs");
include!("evidence/parsed_documents.rs");
include!("evidence/raw_documents.rs");
include!("evidence/fixture_parsers.rs");
include!("evidence/profile_runner.rs");
include!("evidence/release_model.rs");
include!("evidence/artifact_facts.rs");
include!("evidence/release_validators.rs");
include!("evidence/release_rendering.rs");
include!("evidence/negative_fixtures.rs");
include!("evidence/persistence.rs");
include!("evidence/tests.rs");
