[package]
name = "vb_runtime"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
crossbeam-queue.workspace = true
indexmap.workspace = true
rtrb.workspace = true
thiserror.workspace = true
vb_core = { path = "../vb_core" }
vb_storage = { path = "../vb_storage" }
postcard.workspace = true

[dev-dependencies]
proptest = { workspace = true }
tempfile.workspace = true
vb_core = { path = "../vb_core", features = ["test-util"] }

[lints]
workspace = true
