[package]
name = "vb-benchmark-fuzz"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[features]
fuzz = []

[dependencies]
libfuzzer-sys.workspace = true
vb_yaml = { path = "../../crates/vb_yaml" }
vb_compile = { path = "../../crates/vb_compile" }
vb_ipc = { path = "../../crates/vb_ipc" }

[lib]
name = "vb_benchmark_fuzz_lib"
path = "src/lib.rs"
