[package]
name = "vb_validate"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
thiserror.workspace = true
vb_core = { path = "../vb_core" }
vb_yaml = { path = "../vb_yaml" }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }

[features]
default = []
verus = []

[lints]
workspace = true
