// Fuzz target: canonical_digest_ask.rs
// PO: PO-FUZZ-001 — canonical_digest with Ask primitives robust against adversarial input
// Bead: vb-xi2f.33 / P1: digest covers ask semantics
// Verifier: cargo-fuzz (libfuzzer)
// Command: cargo fuzz run canonical_digest_ask -- -max_len=65536 -runs=100000
//
// Proof obligations:
// - PO-FUZZ-001: Fuzz canonical_digest with adversarial WorkflowSource inputs
//   containing Ask primitives. Verify no crash, panic, OOM, or hang.
//
// GOD RULE 1: Uses libfuzzer-generated bytes to construct WorkflowSource values.
// GOD RULE 2: Binds to actual Rust canonical_digest() implementation.

#![no_main]

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    fuzz_canonical_digest_ask(data);
});

/// Reconstruct a WorkflowSource from arbitrary fuzz bytes and verify digest behavior.
fn fuzz_canonical_digest_ask(data: &[u8]) {
    // Use raw bytes as prompt content; truncate to reasonable bounds
    let prompt = match std::str::from_utf8(data) {
        Ok(s) => s.to_string(),
        Err(_) => String::from_utf8_lossy(data).into_owned(),
    };

    // Bound prompt to prevent OOM on adversarial large inputs
    let prompt: String = prompt.chars().take(4096).collect();

    // Extract timeout from first byte: 0=no timeout, 1=empty timeout, 2+=use rest as timeout
    let timeout: Option<String> = data.first().copied().map_or(None, |b| match b {
        0 => None,
        1 => Some(String::new()),
        _ => {
            if data.len() > 1 {
                let timeout_bytes = &data[1..];
                let timeout_str = String::from_utf8_lossy(timeout_bytes).into_owned();
                let bounded: String = timeout_str.chars().take(256).collect();
                if bounded.is_empty() {
                    None
                } else {
                    Some(bounded)
                }
            } else {
                None
            }
        }
    });

    // Reconstruct the source
    use vb_yaml::ast::{StepAst, StepPrimitive, TriggerAst, WorkflowSource, WorkflowSourceParts};

    let steps = vec![StepAst {
        id: "fuzz_ask".to_string(),
        name: None,
        condition: None,
        primitive: StepPrimitive::Ask {
            prompt: prompt.clone(),
            timeout: timeout.clone(),
        },
        with: None,
        retry: None,
        on_error: None,
        then: None,
    }];

    let source = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        WorkflowSource::new(WorkflowSourceParts {
            version: "velvet-ballastics/v1".to_string(),
            name: "fuzz_workflow".to_string(),
            trigger: TriggerAst::Manual,
            inputs: vec![],
            vars: vec![],
            secrets: vec![],
            steps,
            result: None,
            examples: vec![],
        })
    })) {
        Ok(s) => s,
        Err(_) => return, // Construction failure: invalid input, not a digest bug
    };

    // Invoke canonical_digest under panic catch
    use vb_compile::canonical_digest;

    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        canonical_digest(&source)
    }));

    match result {
        Ok(digest_first) => {
            // Verify determinism: same source produces same digest
            let digest_second = canonical_digest(&source);
            assert_eq!(
                digest_first, digest_second,
                "PO-FUZZ-001 violated: canonical_digest non-deterministic for fuzz input"
            );

            // Verify the digest is well-formed (32 bytes)
            assert_eq!(
                digest_first.as_bytes().len(),
                32,
                "PO-FUZZ-001 violated: WorkflowDigest has wrong byte length"
            );
        }
        Err(panic_payload) => {
            // Extract panic message if possible
            let msg = panic_payload
                .downcast_ref::<String>()
                .map(|s| s.as_str())
                .or_else(|| panic_payload.downcast_ref::<&str>().copied())
                .unwrap_or("(unknown panic payload)");
            panic!(
                "PO-FUZZ-001 FAILED: canonical_digest panicked on Ask input: {}",
                msg
            );
        }
    }
}
