#![forbid(unsafe_code)]
//! Scalar post-decode admission kernel shared by compiled slug/query validation.
//!
//! GENERATED by `verification/verus/generate_vb_ajc40_admission_kernel.py`.
//! Source: `verification/verus/vb_ajc40_admission_kernel.source`.
//! Source sha256: e8cd350a9a0ffb712c163e5e3f327d69d148f3d361ade443546d9964efdeea8d.
//! Verus output: `verification/verus/vb_ajc40_admission_kernel_scalar.rs`.

/// Scalar admission decision for decoded bounded-accessor collections.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AdmissionKernelError {
    /// Decoded collection has more entries than the production hard limit.
    TooManyItems,
    /// At least one decoded path exceeds the production path-depth limit.
    PathTooDeep,
    /// Recomputed per-item yield total does not match serialized metadata.
    TotalYieldCostMismatch,
    /// Recomputed yield total exceeds caller admission budget.
    YieldBudgetExceeded,
}

/// Validates count/path/total/budget admission facts and returns remaining budget.
///
/// This function is deliberately scalar and side-effect free so production slug
/// and query validators can share one deterministic seam after postcard decode
/// and checked per-item total recomputation.
pub const fn validate_admission_summary(
    count: usize,
    max_count: usize,
    max_path_depth: usize,
    max_path_segments: usize,
    recomputed_total: u64,
    declared_total_yield_cost: u64,
    max_yield_budget: u64,
) -> Result<u64, AdmissionKernelError> {
    if count > max_count {
        return Err(AdmissionKernelError::TooManyItems);
    }
    validate_admission_depth_total_budget(
        max_path_depth,
        max_path_segments,
        recomputed_total,
        declared_total_yield_cost,
        max_yield_budget,
    )
}

const fn validate_admission_depth_total_budget(
    max_path_depth: usize,
    max_path_segments: usize,
    recomputed_total: u64,
    declared_total_yield_cost: u64,
    max_yield_budget: u64,
) -> Result<u64, AdmissionKernelError> {
    if max_path_depth > max_path_segments {
        return Err(AdmissionKernelError::PathTooDeep);
    }
    if declared_total_yield_cost != recomputed_total {
        return Err(AdmissionKernelError::TotalYieldCostMismatch);
    }
    remaining_yield_budget(recomputed_total, max_yield_budget)
}

const fn remaining_yield_budget(
    recomputed_total: u64,
    max_yield_budget: u64,
) -> Result<u64, AdmissionKernelError> {
    match max_yield_budget.checked_sub(recomputed_total) {
        Some(remaining) => Ok(remaining),
        None => Err(AdmissionKernelError::YieldBudgetExceeded),
    }
}

/// Adds one per-item yield cost to an accumulated total with overflow rejection.
pub const fn accumulate_yield_cost(
    total: u64,
    item_cost: u64,
) -> Result<u64, AdmissionKernelError> {
    match total.checked_add(item_cost) {
        Some(next) => Ok(next),
        None => Err(AdmissionKernelError::YieldBudgetExceeded),
    }
}
